klookva_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: KlookvaUserBundle:Default:index }

fos_user_register:
    pattern:  /register
    defaults: { _controller: KlookvaUserBundle:Registration:register }    

fos_user_registration_register:
    pattern: /
    defaults: {_controller: FOSUserBundle:Registration:register}
